apiVersion: apps/v1
kind: Deployment
metadata:
  name: tech-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tech-service
  template:
    metadata:
      labels:
        app: tech-service
    spec:
      containers:
        - name: tech-service
          image: tech-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          volumeMounts: 
            - name: config-volume
              mountPath: /app/config
          readinessProbe:
            httpGet:
              path: /tech-service/actuator/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /tech-service/actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
      volumes: # Add volumes section
        - name: config-volume
          configMap:
            # reference the ConfigMap name created in step 1
            name: tech-service-config