server:
  port: 8080
  servlet:
    context-path: /dispatch-service
spring:
  application:
    name: dispatch-service
  datasource:
    url: jdbc:h2:mem:dispatchdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    initialization-mode: always
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
management:
  endpoints:
    web:
      exposure:
        include: health