apiVersion: apps/v1
kind: Deployment
metadata:
  name: dispatch-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dispatch-service
  template:
    metadata:
      labels:
        app: dispatch-service
    spec:
      containers:
        - name: dispatch-service
          image: dispatch-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080