apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: job-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  ingressClassName: nginx
  rules:
    - host: demo.localhost
      http:
        paths:
          - path: /job-service
            pathType: Prefix
            backend:
              service:
                name: job-service
                port:
                  number: 8080