apiVersion: v1
kind: Service
metadata:
  name: ui-service
spec:
  type: ClusterIP
  selector:
    app: ui-service
    instance: ui-service
  sessionAffinity: None
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      name: http
